INPUT_QUEUE_NAME_KEY = 'PROCESSED_PAGES_QUEUE'
DB_URL_KEY = 'ELASTIC_URL'
CREDS_LOGIN_KEY = 'ELASTIC_LOGIN'
CREDS_PASS_KEY = 'ELASTIC_PASS'

MQ_HOST_KEY = 'MQ_HOST'
MQ_PORT_KEY = 'MQ_PORT'
MQ_USER_KEY = 'MQ_USER'
MQ_PASS_KEY = 'MQ_PASS'


INTERVAL = 20
MAX_INSTANCES = 1
