INPUT_QUEUE_NAME_KEY = 'URLS_QUEUE'
OUTPUT_QUEUE_NAME_KEY = 'DOWNLOADED_PAGES_QUEUE'

MQ_HOST_KEY = 'MQ_HOST'
MQ_PORT_KEY = 'MQ_PORT'
MQ_USER_KEY = 'MQ_USER'
MQ_PASS_KEY = 'MQ_PASS'


INTERVAL = 3600
MAX_INSTANCES = 1
