INPUT_QUEUE_NAME_KEY = 'DOWNLOADED_PAGES_QUEUE'
OUTPUT_QUEUE_NAME_KEY = 'PARSED_PAGES_QUEUE'
DOWNLOADER_QUEUE = 'URLS_QUEUE'

MQ_HOST_KEY = 'MQ_HOST'
MQ_PORT_KEY = 'MQ_PORT'
MQ_USER_KEY = 'MQ_USER'
MQ_PASS_KEY = 'MQ_PASS'

INTERVAL = 1800
MAX_INSTANCES = 1
